name: Buildkit
on: [push]

permissions:
  contents: read
  pull-requests: read

jobs:
  commitlint:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/shyim/buildkit:4
      options: --security-opt seccomp=unconfined --security-opt apparmor=unconfined
    steps:
      - run: |
          cat <<EOF >> Dockerfile
          FROM debian
          RUN apt-get update && apt-get install -y git
          EOF
        working-directory: /tmp
      - run: buildctl-daemonless.sh build --frontend dockerfile.v0 --local context=. --local dockerfile=. --output type=local,dest=/tmp/.test .
        working-directory: /tmp
