name: Buildkit
on: [push]

permissions:
  contents: read
  pull-requests: read

jobs:
  commitlint:
    runs-on: ubuntu-latest
    container:
      image: alpine
    services:
      buildkitd:
        image: ghcr.io/shyim/buildkit
        options: --security-opt seccomp=unconfined --security-opt apparmor=unconfined
        ports:
          - 1234:1234
    steps:
      - run: apk add --no-cache buildctl
      - run: |
          cat <<EOF >> Dockerfile
          FROM debian
          RUN apt-get update && apt-get install -y git
          EOF
      - run: buildctl --addr tcp://127.0.0.1:1234 build --frontend dockerfile.v0 --local context=. --local dockerfile=. --output type=local,dest=/tmp/.test .
